services:
  api:
    image: "0x6a616e/pef-api:latest"
    volumes:
      - images:/app/images
    ports:
      - "5000:80"
    deploy:
      update_config:
        order: start-first
  frontend:
    image: "0x6a616e/pef-frontend:latest"
    ports:
      - "8080:80"
    deploy:
      update_config:
        order: start-first

volumes:
  images:
