services:
  backend:
    environment:
      MODEL_PATH: "models/UNet.pth"
      IMAGES_FOLDER: "images"
      MONGO_URL: "mongodb://mongodb:27017"
    image: "0x6a616e/pef-backend:latest"
    volumes:
      - images:/app/images
      - models:/app/models
    ports:
      - "5000:80"
    deploy:
      update_config:
        order: start-first
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    deploy:
      update_config:
        order: start-first

volumes:
  images:
  models:
  mongodb_data:
